//! Generated by `codegen_payloads`, do not edit by hand.

use serde::Serialize;

use crate::types::{ChatJoinRequestQueryResult, True};

impl_payload! {
    /// Use this method to process a received chat join request query. Returns _True_ on success.
    #[derive(Debug, PartialEq, Eq, Hash, Clone, Serialize)]
    pub AnswerChatJoinRequestQuery (AnswerChatJoinRequestQuerySetters) => True {
        required {
            /// Unique identifier of the join request query
            pub chat_join_request_query_id: String [into],
            /// Result of the query. Must be _approve_, _decline_, or _queue_ (leave the decision to other administrators).
            pub result: ChatJoinRequestQueryResult,
        }
    }
}
