//! Generated by `codegen_payloads`, do not edit by hand.

use serde::Serialize;

use crate::types::{MessageId, Recipient, True};

impl_payload! {
    /// Use this method to delete an ephemeral message. Returns True on success.
    #[derive(Debug, PartialEq, Eq, Hash, Clone, Serialize)]
    pub DeleteEphemeralMessage (DeleteEphemeralMessageSetters) => True {
        required {
            /// Unique identifier for the target chat or username of the target channel (in the format `@channelusername`).
            pub chat_id: Recipient [into],
            /// Identifier of the user who received the message
            pub receiver_user_id: i64,
            /// Unique identifier of the ephemeral message to delete
            #[serde(with = "crate::types::msg_id_as_int")]
            pub ephemeral_message_id: MessageId,
        }
    }
}
