//! Generated by `codegen_payloads`, do not edit by hand.

use serde::Serialize;

use crate::types::{InlineKeyboardMarkup, MessageId, Recipient, True};

impl_payload! {
    /// Use this method to edit only the reply markup of an ephemeral message. Returns True on success.
    #[derive(Debug, PartialEq, Eq, Hash, Clone, Serialize)]
    pub EditEphemeralMessageReplyMarkup (EditEphemeralMessageReplyMarkupSetters) => True {
        required {
            /// Unique identifier for the target chat or username of the target channel (in the format `@channelusername`).
            pub chat_id: Recipient [into],
            /// Identifier of the user who received the message
            pub receiver_user_id: i64,
            /// Unique identifier of the ephemeral message to edit
            #[serde(with = "crate::types::msg_id_as_int")]
            pub ephemeral_message_id: MessageId,
        }
        optional {
            /// A JSON-serialized object for an [inline keyboard].
            ///
            /// [inline keyboard]: https://core.telegram.org/bots#inline-keyboards-and-on-the-fly-updating
            pub reply_markup: InlineKeyboardMarkup,
        }
    }
}
