//! Generated by `codegen_payloads`, do not edit by hand.

use serde::Serialize;

use crate::types::{InlineKeyboardMarkup, InputMedia, MessageId, Recipient, True};

impl_payload! {
    @[multipart = media]
    /// Use this method to edit the media of an ephemeral message. Returns True on success.
    #[derive(Debug, Clone, Serialize)]
    pub EditEphemeralMessageMedia (EditEphemeralMessageMediaSetters) => True {
        required {
            /// Unique identifier for the target chat or username of the target channel (in the format `@channelusername`).
            pub chat_id: Recipient [into],
            /// Identifier of the user who received the message
            pub receiver_user_id: i64,
            /// Unique identifier of the ephemeral message to edit
            #[serde(with = "crate::types::msg_id_as_int")]
            pub ephemeral_message_id: MessageId,
            /// A JSON-serialized object for the new media content of the message. A new file can't be uploaded; use a previously uploaded file via its file_id or specify a URL.
            pub media: InputMedia,
        }
        optional {
            /// A JSON-serialized object for an [inline keyboard].
            ///
            /// [inline keyboard]: https://core.telegram.org/bots#inline-keyboards-and-on-the-fly-updating
            pub reply_markup: InlineKeyboardMarkup,
        }
    }
}
