//! Generated by `codegen_payloads`, do not edit by hand.

use serde::Serialize;

use crate::types::{InlineKeyboardMarkup, MessageEntity, MessageId, ParseMode, Recipient, True};

impl_payload! {
    /// Use this method to edit the caption of an ephemeral message. Returns True on success.
    #[derive(Debug, PartialEq, Eq, Hash, Clone, Serialize)]
    pub EditEphemeralMessageCaption (EditEphemeralMessageCaptionSetters) => True {
        required {
            /// Unique identifier for the target chat or username of the target channel (in the format `@channelusername`).
            pub chat_id: Recipient [into],
            /// Identifier of the user who received the message
            pub receiver_user_id: i64,
            /// Unique identifier of the ephemeral message to edit
            #[serde(with = "crate::types::msg_id_as_int")]
            pub ephemeral_message_id: MessageId,
        }
        optional {
            /// New caption of the message, 0-1024 characters after entities parsing
            pub caption: String [into],
            /// Mode for parsing entities in the message text. See [formatting options] for more details.
            ///
            /// [formatting options]: https://core.telegram.org/bots/api#formatting-options
            pub parse_mode: ParseMode,
            /// List of special entities that appear in the caption, which can be specified instead of _parse\_mode_
            pub caption_entities: Vec<MessageEntity> [collect],
            /// Pass True if the caption must be shown above the message media. Supported only for animation, photo and video messages
            pub show_caption_above_media: bool,
            /// A JSON-serialized object for an [inline keyboard].
            ///
            /// [inline keyboard]: https://core.telegram.org/bots#inline-keyboards-and-on-the-fly-updating
            pub reply_markup: InlineKeyboardMarkup,
        }
    }
}
