//! Generated by `codegen_payloads`, do not edit by hand.

use serde::Serialize;

use crate::types::{ChatId, InputRichMessage, ThreadId, True};

impl_payload! {
    @[multipart = rich_message]
    /// Use this method to stream a partial rich message to a user while the message is being generated. On success, _True_ is returned.
    #[derive(Debug, Clone, Serialize)]
    pub SendRichMessageDraft (SendRichMessageDraftSetters) => True {
        required {
            /// Unique identifier for the target private chat
            pub chat_id: ChatId [into],
            /// Unique identifier of the message draft; must be non-zero. Same-id changes are animated
            pub draft_id: i64,
            /// The partial message to be streamed
            pub rich_message: InputRichMessage,
        }
        optional {
            /// Unique identifier for the target message thread (topic) of the forum; for forum supergroups only
            pub message_thread_id: ThreadId,
            /// Pass True to show the user a button to stop further drafts
            pub can_stop: bool,
            /// Pass True to keep the draft in the chat when the button is pressed
            pub keep_on_stop: bool,
        }
    }
}
